version = 0.1
[preview-clab]
[preview-clab.deploy]
[preview-clab.deploy.parameters]
stack_name = "cns-cba-org-stackset-preview-clab"
s3_bucket = "cns-cba-org-stackset-deployment-bucket-111111111"
s3_prefix = "preview-clab"
region = "ap-southeast-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
parameter_overrides = "EnvironmentType=\"preview-clab\" Environment=\"preview\" OrganisationID=\"ou-111111111,ou-111111111\" RemediationChecksum=\"111111111\""
image_repositories = []
disable_rollback = false
[preview-nonp]
[preview-nonp.deploy]
[preview-nonp.deploy.parameters]
stack_name = "cns-cba-org-stackset-preview-nonp"
s3_bucket = "cns-cba-org-stackset-deployment-bucket-111111111"
s3_prefix = "preview-nonp"
region = "ap-southeast-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
parameter_overrides = "EnvironmentType=\"preview-nonp\" Environment=\"preview\" OrganisationID=\"ou-111111111,ou-111111111c\" RemediationChecksum=\"111111111\""
image_repositories = []
disable_rollback = false
[ga-clab]
[ga-clab.deploy]
[ga-clab.deploy.parameters]
stack_name = "cns-cba-org-stackset-ga-clab"
s3_bucket = "cns-cba-org-stackset-deployment-bucket-111111111"
s3_prefix = "ga-clab"
region = "ap-southeast-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
parameter_overrides = "EnvironmentType=\"ga-clab\" Environment=\"clab\" OrganisationID=\"ou-y57b-111111111,ou-y57b-111111111\" RemediationChecksum=\"111111111\""
image_repositories = []
disable_rollback = false
[ga-nonp]
[ga-nonp.deploy]
[ga-nonp.deploy.parameters]
stack_name = "cns-cba-org-stackset-ga-nonp"
s3_bucket = "cns-cba-org-stackset-deployment-bucket-111111111"
s3_prefix = "ga-nonp"
region = "ap-southeast-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
parameter_overrides = "EnvironmentType=\"ga-nonp\" Environment=\"nonp\" OrganisationID=\"ou-y57b-111111111\" RemediationChecksum=\"111111111\""
image_repositories = []
disable_rollback = false
[ga-prod]
[ga-prod.deploy]
[ga-prod.deploy.parameters]
stack_name = "cns-cba-org-stackset-ga-prod"
s3_bucket = "cns-cba-org-stackset-deployment-bucket-111111111"
s3_prefix = "ga-prod"
region = "ap-southeast-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
parameter_overrides = "EnvironmentType=\"ga-prod\" Environment=\"prod\" OrganisationID=\"ou-111111111\" RemediationChecksum=\"111111111\""
image_repositories = []
disable_rollback = false
